# compile options
FC = gfortran
FCFLAGS = -O3
FLIBS = 
LPATH = 
IPATH = 
OBJS = test_funcs.o
MAIN = ftest_nompi.f90

# build main program
ftest_nompi : $(MAIN) $(OBJS)
	$(FC) $(FCFLAGS) -o $@ $^ $(LPATH) $(IPATH) $(FLIBS)

# compile objects
%.o : %.f90
	$(FC) $(FCFLAGS) -c $< $(LPATH) $(IPATH) $(FLIBS)

clean :
	rm ftest_nompi *.o
